### ISSUE TITLE
violent crash when passing a meta object without a message as sole parameter

### ISSUE THREAD

**Issue by osher** [logzio/winston-logzio#39]
violent crash when passing a meta object without a message as sole parameter

```
/home/user/app/winston/lib/winston/logger.js:237
      throw ex;
      ^

TypeError: this.safeToString is not a function
    at LogzioWinstonTransport.log (/home/user/app/winston-logzio/lib/winston-logzio.js:26:23)
    at LogzioWinstonTransport._write (/home/user/app/winston-transport/index.js:81:19)
    at doWrite (/home/user/app/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/user/app/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at LogzioWinstonTransport.Writable.write (/home/user/app/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/home/user/app/winston/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at emitOne (events.js:121:20)
    at DerivedLogger.emit (events.js:211:7)
    at addChunk (/home/user/app/winston/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/home/user/app/winston/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DerivedLogger.Readable.push (/home/user/app/winston/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DerivedLogger.Transform.push (/home/user/app/winston/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DerivedLogger._transform (/home/user/app/winston/lib/winston/logger.js:235:12)
    at DerivedLogger.Transform._read (/home/user/app/winston/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DerivedLogger.Transform._write (/home/user/app/winston/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/user/app/winston/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/user/app/winston/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DerivedLogger.Writable.write (/home/user/app/winston/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.(anonymous function).args (/home/user/app/winston/lib/winston/create-logger.js:54:16)
    at Function.tailormedLogger.(anonymous function).a (/home/osher/tailormed/financial-navigation/application/builder/src/api/api/services/Logger.js:95:16)
    at _writeLogToConsole (/home/user/app/captains-log/lib/write.js:46:20)
    at Function.ship (/home/user/app/sails/lib/hooks/logger/ship.js:16:5)
    at _printSuccessMsg (/home/user/app/sails/lib/app/lift.js:67:33)
    at sailsReady (/home/user/app/sails/lib/app/lift.js:49:5)
    at /home/user/app/sails/node_modules/async/lib/async.js:721:13
    at /home/user/app/sails/node_modules/async/lib/async.js:52:16
    at /home/user/app/sails/node_modules/async/lib/async.js:269:32
    at /home/user/app/sails/node_modules/async/lib/async.js:44:16
    at /home/user/app/sails/node_modules/async/lib/async.js:718:17
    at /home/user/app/sails/node_modules/async/lib/async.js:167:37
    at /home/user/app/sails/lib/app/private/initialize.js:89:14
    at /home/user/app/sails/node_modules/async/lib/async.js:52:16
    at done (/home/user/app/sails/node_modules/async/lib/async.js:246:17)
    at /home/user/app/sails/node_modules/async/lib/async.js:44:16
```

**Comment by osher** [comment]
Happens also when message is an empty string or actually any falsy value

**Comment by osher** [comment]
Happens also when `log.info('')`
(appears like sails banner does that, and fails...)

**Comment by idohalevi** [comment]
@osher can you please share your how you set up the logger?
